import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createClient } from '@supabase/supabase-js';
import './styles.css';

const stages=['To Research','Researching','Designing','Listed in Shopify','Flip Anywhere POD in Shopify','Image Ads Made','Video Ads Made','Copy Made','Ads Launched'];
const seed=[
 {title:'Daughter Milestone Jewelry Dish',recipient:'Daughter',occasion:'Birthday / milestone',product_type:'Jewelry dish',stage:'Researching',priority:'High',notes:'Personalized emotional gift concept.'},
 {title:'Grandma Holiday Platter',recipient:'Grandma',occasion:'Christmas',product_type:'Platter',stage:'To Research',priority:'High',notes:'Holiday gifting angle.'},
 {title:'Best Friend Keepsake',recipient:'Best friend',occasion:'Birthday',product_type:'Gift',stage:'Designing',priority:'Medium',notes:'Warm, cheeky message direction.'}
];
const hasConfig=Boolean(import.meta.env.VITE_SUPABASE_URL&&import.meta.env.VITE_SUPABASE_ANON_KEY);
const supabase=hasConfig?createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_ANON_KEY):null;
function App(){
 const [products,setProducts]=useState([]),[loading,setLoading]=useState(true),[filter,setFilter]=useState(''),[error,setError]=useState(''),[user,setUser]=useState(null),[email,setEmail]=useState('');
 const load=async()=>{setLoading(true);setError('');if(!supabase){setProducts(JSON.parse(localStorage.getItem('annette-products')||'null')||seed);setLoading(false);return}const {data,error}=await supabase.from('products').select('*').order('created_at',{ascending:false});if(error)setError(error.message);else setProducts(data||[]);setLoading(false)};
 useEffect(()=>{if(!supabase){load();return}supabase.auth.getSession().then(({data})=>{setUser(data.session?.user||null);setLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>setUser(session?.user||null));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(user)load()},[user]);
 const login=async(e)=>{e.preventDefault();setError('');const {error}=await supabase.auth.signInWithOtp({email,email,options:{emailRedirectTo:window.location.origin}});if(error)setError(error.message);else setError('Check your email for the secure sign-in link.');};
 const save=async(p)=>{if(!supabase){const next=p.id?products.map(x=>x.id===p.id?p:x):[{...p,id:crypto.randomUUID()},...products];setProducts(next);localStorage.setItem('annette-products',JSON.stringify(next));return}const payload={...p};if(!p.id)delete payload.id;const query=p.id?supabase.from('products').update(payload).eq('id',p.id):supabase.from('products').insert(payload);const {error}=await query;if(error){setError(error.message);return}load()};
 const add=()=>save({title:'New product',recipient:'',occasion:'',product_type:'',stage:'To Research',priority:'Medium',notes:''});
 const visible=products.filter(p=>[p.title,p.recipient,p.occasion,p.product_type,p.stage].join(' ').toLowerCase().includes(filter.toLowerCase()));
 if(hasConfig&&!user)return <main className="login"><p className="eyebrow">PRIVATE WORKSPACE</p><h1>Annette's Product Board</h1><p className="sub">Sign in with your owner email to access the board.</p><form onSubmit={login}><input type="email" required placeholder="you@email.com" value={email} onChange={e=>setEmail(e.target.value)}/><button>Send secure sign-in link</button></form>{error&&<div className="notice">{error}</div>}</main>;
 return <main><header><div><p className="eyebrow">PRODUCT COMMAND CENTER</p><h1>Research to Launch Product Board</h1><p className="sub">Track Sparkle Me Creations products from idea to ads.</p></div><button onClick={add}>+ New product</button></header>{!hasConfig&&<div className="notice">Demo mode: add your Supabase keys in Vercel to save across devices.</div>}{error&&<div className="error">{error}</div>}<input className="search" placeholder="Search products, recipients, occasions…" value={filter} onChange={e=>setFilter(e.target.value)}/>{loading?<p>Loading board…</p>:<section className="board">{stages.map(stage=><div className="column" key={stage}><h2>{stage}<span>{visible.filter(p=>p.stage===stage).length}</span></h2>{visible.filter(p=>p.stage===stage).map(p=><article key={p.id}><input aria-label="Product title" value={p.title} onChange={e=>setProducts(products.map(x=>x.id===p.id?{...x,title:e.target.value}:x))} onBlur={e=>save({...p,title:e.target.value})}/><select value={p.stage} onChange={e=>save({...p,stage:e.target.value})}>{stages.map(s=><option key={s}>{s}</option>)}</select><select value={p.priority} onChange={e=>save({...p,priority:e.target.value})}><option>High</option><option>Medium</option><option>Low</option></select><textarea placeholder="Notes" value={p.notes||''} onChange={e=>setProducts(products.map(x=>x.id===p.id?{...x,notes:e.target.value}:x))} onBlur={e=>save({...p,notes:e.target.value})}/></article>)}<button className="add" onClick={()=>save({title:'New product',stage,priority:'Medium',notes:''})}>+ Add product</button></div>)}</section>}</main>}
createRoot(document.getElementById('root')).render(<App/>);
